package.name = "reliq"
package.description = "A portable library of primitive-like constructs."
package.version = "0.2.8"
package.edition = "2024"
package.license = "Apache-2.0"
package.readme = "readme.md"
package.publish = true
package.keywords = [
    "arithmetic",
    "math",
    "portable"
]
dependencies.modwire.version = ">=0.1.0,<1.0.0"
dependencies.paste.version = ">=1.0.15,<2.0.0"
dev-dependencies.criterion.version = ">=0.7.0,<1.0.0"
dev-dependencies.rstest.version = ">=0.26.1,<1.0.0"
features.default = ["std"]
features.std = []

[[bench]]
name = "q"
harness = false