pub trait PrimIntConversion
where
    Self: ::core::convert::TryFrom<i8>,
    Self: ::core::convert::TryFrom<i16>,
    Self: ::core::convert::TryFrom<i32>,
    Self: ::core::convert::TryFrom<i64>,
    Self: ::core::convert::TryFrom<i128>,
    Self: ::core::convert::TryFrom<isize>,
    Self: ::core::convert::TryFrom<u8>,
    Self: ::core::convert::TryFrom<u16>,
    Self: ::core::convert::TryFrom<u32>,
    Self: ::core::convert::TryFrom<u64>,
    Self: ::core::convert::TryFrom<u128>,
    Self: ::core::convert::TryFrom<usize>,
    Self: ::core::convert::TryInto<i8>,
    Self: ::core::convert::TryInto<i16>,
    Self: ::core::convert::TryInto<i32>,
    Self: ::core::convert::TryInto<i64>,
    Self: ::core::convert::TryInto<i128>,
    Self: ::core::convert::TryInto<isize>,
    Self: ::core::convert::TryInto<u8>,
    Self: ::core::convert::TryInto<u16>,
    Self: ::core::convert::TryInto<u32>,
    Self: ::core::convert::TryInto<u64>,
    Self: ::core::convert::TryInto<u128>,
    Self: ::core::convert::TryInto<usize> 
{}

impl<T> PrimIntConversion for T 
where
    Self: ::core::convert::TryFrom<i8>,
    Self: ::core::convert::TryFrom<i16>,
    Self: ::core::convert::TryFrom<i32>,
    Self: ::core::convert::TryFrom<i64>,
    Self: ::core::convert::TryFrom<i128>,
    Self: ::core::convert::TryFrom<isize>,
    Self: ::core::convert::TryFrom<u8>,
    Self: ::core::convert::TryFrom<u16>,
    Self: ::core::convert::TryFrom<u32>,
    Self: ::core::convert::TryFrom<u64>,
    Self: ::core::convert::TryFrom<u128>,
    Self: ::core::convert::TryFrom<usize>,
    Self: ::core::convert::TryInto<i8>,
    Self: ::core::convert::TryInto<i16>,
    Self: ::core::convert::TryInto<i32>,
    Self: ::core::convert::TryInto<i64>,
    Self: ::core::convert::TryInto<i128>,
    Self: ::core::convert::TryInto<isize>,
    Self: ::core::convert::TryInto<u8>,
    Self: ::core::convert::TryInto<u16>,
    Self: ::core::convert::TryInto<u32>,
    Self: ::core::convert::TryInto<u64>,
    Self: ::core::convert::TryInto<u128>,
    Self: ::core::convert::TryInto<usize> 
{}