/// `A` must not overflow or panic on any op.
pub trait Precision<const A: u8> {}
impl Precision<1> for () {}
impl Precision<2> for () {}
impl Precision<3> for () {}
impl Precision<4> for () {}
impl Precision<5> for () {}
impl Precision<6> for () {}
impl Precision<7> for () {}
impl Precision<8> for () {}
impl Precision<9> for () {}
impl Precision<10> for () {}
impl Precision<11> for () {}
impl Precision<12> for () {}
impl Precision<13> for () {}
impl Precision<14> for () {}
impl Precision<15> for () {}
impl Precision<16> for () {}
impl Precision<17> for () {}
impl Precision<18> for () {}
impl Precision<19> for () {}
impl Precision<20> for () {}
impl Precision<21> for () {}
impl Precision<22> for () {}
impl Precision<23> for () {}
impl Precision<24> for () {}
impl Precision<25> for () {}
impl Precision<26> for () {}
impl Precision<27> for () {}
impl Precision<28> for () {}
impl Precision<29> for () {}
impl Precision<30> for () {}
impl Precision<31> for () {}
impl Precision<32> for () {}
impl Precision<33> for () {}
impl Precision<34> for () {}
impl Precision<35> for () {}
impl Precision<36> for () {}
impl Precision<37> for () {}