::modwire::expose!(
    pub acos
    pub asin
    pub atan
    pub bits
    pub bound
    pub checked_add
    pub checked_div
    pub checked_mul
    pub checked_neg
    pub checked_rem
    pub checked_shl
    pub checked_shr
    pub checked_sub
    pub checked
    pub cos
    pub float
    pub int
    pub overflowing_add
    pub overflowing_div
    pub overflowing_mul
    pub overflowing_neg
    pub overflowing_rem
    pub overflowing_shl
    pub overflowing_shr
    pub overflowing_sub
    pub overflowing
    pub prim_float_conversion
    pub prim_int_conversion
    pub prim
    pub quick_access
    pub sign
    pub signed
    pub sin
    pub sqrt
    pub tan
    pub trig
    pub trig_hyperbolic
    pub trig_reciprocal
    pub unsigned
    pub wrapping_add
    pub wrapping_div
    pub wrapping_mul
    pub wrapping_neg
    pub wrapping_pow
    pub wrapping_rem
    pub wrapping_sub
    pub wrapping
);

